name: zarzasr

services:

  # 2. Vue Frontend
  frontend:
    build: ./frontend
    restart: always
    networks:
      - default
      - shared_net

  # 3. Bun + Hono Backend
  backend:
    build: ./backend
    restart: always
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/mydb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  # 4. Postgres Database
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_service_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Optional: map to host if you want to use local DB GUIs

  # 5. Redis Cache
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_service_data:/data

networks:
  shared_net:
    external: true
    name: shared_gateway_net

volumes:
  postgres_service_data:
  redis_service_data:
